## Neural Network Topology [Feedforward]

#### Q1 Write a Python Program to train the following Neural Network with single neuron. Let you start to train the network with w=3, 6 and 9.

In [1]:
import numpy as np

train_inputs = np.array([0,1,2,3,4])
train_outputs = np.array([0, 6, 12, 18,24])
for i in range(3):
    Weight=int(input("Enter the Value of Weight"))
    pred_output=train_inputs*Weight
    error=pred_output-train_outputs
    squared_error = error**2
    mse = np.mean(squared_error)
    print("Predicted Output: ",pred_output)
    print("Desired Output: ",train_outputs)
    print("Errors",error)
    print("Squared Errors", squared_error)
    print("Mean Squared Errors", mse)

Enter the Value of Weight 3


Predicted Output:  [ 0  3  6  9 12]
Desired Output:  [ 0  6 12 18 24]
Errors [  0  -3  -6  -9 -12]
Squared Errors [  0   9  36  81 144]
Mean Squared Errors 54.0


Enter the Value of Weight 6


Predicted Output:  [ 0  6 12 18 24]
Desired Output:  [ 0  6 12 18 24]
Errors [0 0 0 0 0]
Squared Errors [0 0 0 0 0]
Mean Squared Errors 0.0


Enter the Value of Weight 9


Predicted Output:  [ 0  9 18 27 36]
Desired Output:  [ 0  6 12 18 24]
Errors [ 0  3  6  9 12]
Squared Errors [  0   9  36  81 144]
Mean Squared Errors 54.0


#### Q2 Construct a Feedforward Network with Single Neuron and 3 inputs

In [2]:
D = np.array([[1, 2, 3], #dataset
            [1, 0, 2],
            [0, 1, 4],
            [2, 1, 4]])

#initialize weight matrix
np.random.seed(1)
w = np.random.random((3,1))
print("Weighted Matrix : ")
print(w)

#Forward Pass
for iteration in range(1):
    iLayer = D
    oPer = np.dot(iLayer, w) #Perception
    oLayer = 1/(1+np.exp(-oPer)) #Sigmoid
    
print("Input: ")
print(D)
print("Predicted Output: ")
print(oLayer)

Weighted Matrix : 
[[4.17022005e-01]
 [7.20324493e-01]
 [1.14374817e-04]]
Input: 
[[1 2 3]
 [1 0 2]
 [0 1 4]
 [2 1 4]]
Predicted Output: 
[[0.86506531]
 [0.60282519]
 [0.67277919]
 [0.82560966]]


#### Q3 Construct a Feed forward Network using Two Neurons in the output layer and 3 neurons in the input layer

In [3]:
D = np.array([[1, 2, 3], #dataset
            [1, 0, 2],
            [0, 1, 4],
            [2, 1, 4]])

#initialize weight matrix
np.random.seed(1)
w = np.random.random((3,2))
print("Weighted Matrix : ")
print(w)

#Forward Pass
for iteration in range(1):
    iLayer = D
    oPer = np.dot(iLayer, w) #Perception
    oLayer = 1/(1+np.exp(-oPer)) #Sigmoid
    
print("Input: ")
print(D)
print("Predicted Output: ")
print(oLayer)

Weighted Matrix : 
[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02]]
Input: 
[[1 2 3]
 [1 0 2]
 [0 1 4]
 [2 1 4]]
Predicted Output: 
[[0.70214192 0.83229848]
 [0.6705191  0.71197626]
 [0.64270819 0.66188079]
 [0.80552364 0.8920964 ]]


#### Q4 Construct a Feed forward Network using Two Neurons in the output layer, 3 neurons in the input layer and 4 neuron in the hidden layer

In [4]:
D = np.array([[1, 2, 3], #dataset
            [1, 0, 2],
            [0, 1, 4],
            [2, 1, 4]])

#initialize weight matrix
np.random.seed(1)
W = np.random.random((3,4))
print("W Weighted Matrix : ")
print(W)

print("V Weighted Matrix : ")
V = np.random.random((4,2))
print(V)

for iteration in range(1):
    iLayer = D
    
    hP = np.dot(iLayer, W) #Hidden Layer
    hLayer = 1/(1+np.exp(-hP)) 
    
    oP = np.dot(hLayer, V)
    oLayer = 1/(1+np.exp(-oP)) #Output Layer
    
print("Input: ")
print(D)
print("Predicted Output: ")
print(oLayer)

W Weighted Matrix : 
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]]
V Weighted Matrix : 
[[0.20445225 0.87811744]
 [0.02738759 0.67046751]
 [0.4173048  0.55868983]
 [0.14038694 0.19810149]]
Input: 
[[1 2 3]
 [1 0 2]
 [0 1 4]
 [2 1 4]]
Predicted Output: 
[[0.66512221 0.88502169]
 [0.64349012 0.85918454]
 [0.66686308 0.88347877]
 [0.67146728 0.89535013]]
